# Generated by Django 3.2.7 on 2022-02-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_comment',
            name='article',
        ),
        migrations.DeleteModel(
            name='TB_Article',
        ),
        migrations.DeleteModel(
            name='TB_Comment',
        ),
    ]
