# Generated by Django 3.2.7 on 2022-04-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0003_auto_20220214_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
