# Generated by Django 3.2.7 on 2022-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0004_tb_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_email',
            options={'verbose_name': 'TB_Email', 'verbose_name_plural': 'TB_Emails'},
        ),
        migrations.AlterField(
            model_name='tb_email',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
