# Generated by Django 3.2.7 on 2022-04-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0005_auto_20220416_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_email',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
