# Generated by Django 3.2.7 on 2022-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0006_alter_tb_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_email',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
