# Generated by Django 3.2.7 on 2022-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0007_alter_tb_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_email',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
