# Generated by Django 3.2.7 on 2022-04-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0008_alter_tb_email_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_email',
            old_name='email',
            new_name='mail',
        ),
    ]
