# Generated by Django 3.2.7 on 2022-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbillard', '0009_rename_email_tb_email_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_email',
            name='mail',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
