# Generated by Django 3.2.7 on 2022-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_ue',
            options={'ordering': ('-created_at',), 'verbose_name': 'TB_UE', 'verbose_name_plural': 'TB_UEs'},
        ),
        migrations.RenameField(
            model_name='tb_etudiant',
            old_name='actif',
            new_name='is_active',
        ),
    ]
