# Generated by Django 3.2.7 on 2022-04-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0002_auto_20220329_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_enseignant',
            name='id',
        ),
        migrations.AddField(
            model_name='tb_enseignant',
            name='code',
            field=models.CharField(default=1, max_length=7, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
